/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bhaskara;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Fierro
 */
public class Bhaskara extends javax.swing.JFrame {

    /**
     * Creates new form Bhaskara
     */
    public Bhaskara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstComponentTextField = new javax.swing.JTextField();
        firstComponentLabel = new javax.swing.JLabel();
        secondComponentTextField = new javax.swing.JTextField();
        thirdComponentTextField = new javax.swing.JTextField();
        secondComponentLabel = new javax.swing.JLabel();
        thirdComponentLabel = new javax.swing.JLabel();
        resolveButton = new javax.swing.JButton();
        resultTextField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bhaskara");

        firstComponentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstComponentTextFieldActionPerformed(evt);
            }
        });

        firstComponentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstComponentLabel.setText("x²");

        thirdComponentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdComponentTextFieldActionPerformed(evt);
            }
        });

        secondComponentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        secondComponentLabel.setText("x");

        thirdComponentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thirdComponentLabel.setText("c   = 0");

        resolveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resolveButton.setText("Resolver");
        resolveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveButtonActionPerformed(evt);
            }
        });

        resultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextFieldActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultLabel.setText("Resultado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramon\\Documents\\NetBeansProjects\\Bhaskara\\formula_de_bhaskara.PNG")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(resultLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resolveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(firstComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstComponentLabel)
                        .addGap(16, 16, 16)
                        .addComponent(secondComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondComponentLabel)
                        .addGap(24, 24, 24)
                        .addComponent(thirdComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdComponentLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstComponentLabel)
                    .addComponent(secondComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondComponentLabel)
                    .addComponent(thirdComponentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdComponentLabel))
                .addGap(49, 49, 49)
                .addComponent(resolveButton)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel)
                    .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resolveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveButtonActionPerformed
        // TODO add your handling code here:
        // Zona de declaración de variables
        double discriminante, termino_cuadratico, termino_lineal, constante, res, raiz_doble, primera_raiz, segunda_raiz;
        String prim_raiz, seg_raiz, raices;
        boolean continuar;
        // Zona de inicialización de variables

        if (firstComponentTextField.getText().isEmpty() || secondComponentTextField.getText().isEmpty() || thirdComponentTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Complete los campos vacíos");
        } else {

            termino_cuadratico = Double.parseDouble(firstComponentTextField.getText());
            termino_lineal = Double.parseDouble(secondComponentTextField.getText());
            constante = Double.parseDouble(thirdComponentTextField.getText());
            
            // Primero verifica que se trate de una función cuadrática
            if (termino_cuadratico == 0) {
                resultTextField.setText("El término cuadrático debe ser distinto a cero");
            } else {
                // Calcula el valor del discriminante
                discriminante = calcularDiscriminante(termino_cuadratico, termino_lineal, constante);

                // En relación al discriminante determina el resultado de la ecuación
                if (discriminante < 0) {
                    resultTextField.setText("No existe solución en los reales");
                } else {
                    if (discriminante == 0) {
                        raiz_doble = (-termino_lineal) / (2 * termino_cuadratico);   // Calcula la raíz
                        resultTextField.setText("La raíz doble es: " + raiz_doble);
                    } else {
                        res = Math.sqrt(discriminante); // Aplica la raíz cuadrada al discriminante
                        primera_raiz = (-termino_lineal + res) / (2 * termino_cuadratico);
                        segunda_raiz = (-termino_lineal - res) / (2 * termino_cuadratico);
                        // Casteo a string para luego mostrar los primeros 4 dígitos decimales
                        prim_raiz = String.valueOf(primera_raiz);
                        seg_raiz = String.valueOf(segunda_raiz);

                        raices = determinarRaices(prim_raiz, seg_raiz);

                        resultTextField.setText(raices);

                    }
                }
            }
        }


    }//GEN-LAST:event_resolveButtonActionPerformed

    private void firstComponentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstComponentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstComponentTextFieldActionPerformed

    private void resultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextFieldActionPerformed

    private void thirdComponentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdComponentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdComponentTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Bhaskara().setVisible(true);
            }
        });
        
    }

    /* Métodos propios */
    private static double calcularDiscriminante(double term_cuad, double term_lineal, double constante) {
        /*
        Algoritmo que calcula el discriminante de una ecuación y retorna el resultado
         */
        // Zona de declaración de variable
        double resultado;

        resultado = (term_lineal * term_lineal) - (4 * term_cuad * constante);    // Calcula el discriminante

        return resultado;
    }

    private static String determinarRaices(String prim_raiz, String seg_raiz) {
        /*
        Algoritmo que determina la condición de las raíces para mostrar por pantalla
        las raíces con o sin decimales.        
         */
        // Zona de declaración e inicialización de variable
        String resultado;

        if (prim_raiz.length() > 6) {
            if (seg_raiz.length() > 6) {
                resultado = ("Las raíces son: " + prim_raiz.substring(0, 6) + " y " + seg_raiz.substring(0, 6));
            } else {
                resultado = ("Las raíces son: " + prim_raiz.substring(0, 6) + " y " + seg_raiz);
            }
        } else {
            if (seg_raiz.length() > 6) {
                resultado = ("Las raíces son: " + prim_raiz + " y " + seg_raiz.substring(0, 6));
            } else {
                resultado = ("Las raíces son: " + prim_raiz + " y " + seg_raiz);
            }
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstComponentLabel;
    private javax.swing.JTextField firstComponentTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resolveButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JLabel secondComponentLabel;
    private javax.swing.JTextField secondComponentTextField;
    private javax.swing.JLabel thirdComponentLabel;
    private javax.swing.JTextField thirdComponentTextField;
    // End of variables declaration//GEN-END:variables
}
